import {
  HarvestRecord,
  PaymentRecord,
  ExpenseRecord,
  Garden,
  JobListing,
  CrewLeaderProfile,
  WorkerProfile,
  ServiceProvider,
  ServiceOffer,
  JobApplication,
  FactoryPrice,
  AppSettings,
  AgriProductListing,
  MarketMessage,
  UserAccount,
  AdminUserMessage,
} from "./types";

export const DEFAULT_ADMIN_USER: UserAccount = {
  id: "user-kagan-admin",
  username: "kağan",
  password: "tamer6715",
  fullName: "Kağan (Ana Yönetici)",
  phone: "0543 715 52 00",
  email: "kaganoglu.53@gmail.com",
  role: "admin",
  farmingFocus: "both",
  securityQuestion: "Doğduğunuz şehir neresidir?",
  securityAnswer: "Rize",
  createdAt: "2026-01-01",
};

export const INITIAL_USERS: UserAccount[] = [
  DEFAULT_ADMIN_USER,
  {
    id: "user-mehmet-employer",
    username: "mehmet53",
    password: "123456",
    fullName: "Mehmet Çepni",
    phone: "0532 411 28 53",
    email: "mehmet@tarimcepte.com",
    role: "employer",
    farmingFocus: "tea",
    securityQuestion: "İlk evcil hayvanınızın adı nedir?",
    securityAnswer: "Karabaş",
    createdAt: "2026-02-10",
  },
  {
    id: "user-mustafa-hazelnut",
    username: "mustafa28",
    password: "123456",
    fullName: "Mustafa Çakır",
    phone: "0544 322 19 28",
    email: "mustafa@tarimcepte.com",
    role: "employer",
    farmingFocus: "hazelnut",
    securityQuestion: "İlkokul öğretmeninizin adı nedir?",
    securityAnswer: "Ahmet",
    createdAt: "2026-03-01",
  },
  {
    id: "user-ahmet-producer",
    username: "ahmet53",
    password: "123456",
    fullName: "Ahmet Kavalcı (Bahçe Sahibi)",
    phone: "0532 411 28 53",
    email: "ahmet@tarimcepte.com",
    role: "employer",
    farmingFocus: "tea",
    securityQuestion: "Doğduğunuz sokak?",
    securityAnswer: "Kaptanpaşa",
    createdAt: "2026-03-15",
  },
  {
    id: "user-dursun-crew",
    username: "dursun61",
    password: "123456",
    fullName: "Çavuş Dursun Genç (Ekip Lideri)",
    phone: "0542 611 78 90",
    email: "dursun@tarimcepte.com",
    role: "employer",
    farmingFocus: "both",
    securityQuestion: "En sevdiğiniz yemek?",
    securityAnswer: "Muhlama",
    createdAt: "2026-03-20",
  },
  {
    id: "user-murat-worker",
    username: "murat53",
    password: "123456",
    fullName: "Murat Demir (Usta Hasat İşçisi)",
    phone: "0531 200 45 77",
    email: "murat@tarimcepte.com",
    role: "employer",
    farmingFocus: "tea",
    securityQuestion: "İlk arabanız?",
    securityAnswer: "Toros",
    createdAt: "2026-04-01",
  },
  {
    id: "user-cemal-worker",
    username: "cemal08",
    password: "123456",
    fullName: "Cemal Kaya (Budama Ustası)",
    phone: "0537 912 34 88",
    email: "cemal@tarimcepte.com",
    role: "employer",
    farmingFocus: "tea",
    securityQuestion: "Doğum yeriniz?",
    securityAnswer: "Arhavi",
    createdAt: "2026-04-10",
  },
  {
    id: "user-ismail-beekeeper",
    username: "ismail53",
    password: "123456",
    fullName: "İsmail Koç (Anzer Bal Üreticisi)",
    phone: "0532 555 12 34",
    email: "ismail@tarimcepte.com",
    role: "employer",
    farmingFocus: "both",
    securityQuestion: "Tuttuğunuz takım?",
    securityAnswer: "Rizespor",
    createdAt: "2026-04-15",
  },
  {
    id: "user-fadime-producer",
    username: "fadime61",
    password: "123456",
    fullName: "Fadime Nine (Yerli Üretici)",
    phone: "0538 912 34 56",
    email: "fadime@tarimcepte.com",
    role: "employer",
    farmingFocus: "both",
    securityQuestion: "En sevdiğiniz mevsim?",
    securityAnswer: "İlkbahar",
    createdAt: "2026-04-20",
  },
  {
    id: "user-hakan-agronomist",
    username: "hakan53",
    password: "123456",
    fullName: "Ziraat Müh. Hakan Akın",
    phone: "0464 213 45 67",
    email: "hakan@tarimcepte.com",
    role: "employer",
    farmingFocus: "both",
    securityQuestion: "Mezun olduğunuz lise?",
    securityAnswer: "Rize Fen",
    createdAt: "2026-04-25",
  },
];

export const DEFAULT_APP_SETTINGS: AppSettings = {
  borsaTescilRate: 1.0, // %1 Borsa Tescil
  stopajRate: 1.0, // %1 Stopaj Kesintisi
  autoApplyDeduction: true,
  customDeductionLabel: "Borsa Tescil (%1) + Stopaj (%1)",
  farmerName: "Ahmet K.",
  farmerCksNo: "ÇKS-2026-538192",
  teaLicenseNo: "ÇAYKUR-53-09412",
  defaultCropType: "tea",
  currencySymbol: "TL",
  autoDueDateDays: 30,
};

export const INITIAL_GARDENS: Garden[] = [
  {
    id: "g-1",
    name: "Çayeli Yamaç Çaylığı",
    location: "Rize / Çayeli - Kaptanpaşa",
    sizeDecares: 7.5,
    cropType: "tea",
    bushesCount: 3200,
    adaNo: "104",
    parselNo: "12",
    latitude: 40.9984,
    longitude: 40.7512,
    googleMapsUrl: "https://www.google.com/maps?q=40.9984,40.7512",
    notes: "1. Sürüm yüksek kaliteli mayıs çayı, dik arazi",
  },
  {
    id: "g-2",
    name: "Of Kıyıcık Sahil Çaylığı",
    location: "Trabzon / Of - Kıyıcık",
    sizeDecares: 4.2,
    cropType: "tea",
    bushesCount: 1800,
    adaNo: "218",
    parselNo: "3",
    latitude: 40.9412,
    longitude: 40.2867,
    googleMapsUrl: "https://www.google.com/maps?q=40.9412,40.2867",
    notes: "Düz arazi, makine ile taşımaya elverişli",
  },
  {
    id: "g-3",
    name: "Tirebolu Fındık Bahçesi",
    location: "Giresun / Tirebolu - Doğankent Yolu",
    sizeDecares: 12.0,
    cropType: "hazelnut",
    bushesCount: 450,
    adaNo: "142",
    parselNo: "17",
    latitude: 40.9856,
    longitude: 38.8241,
    googleMapsUrl: "https://www.google.com/maps?q=40.9856,38.8241",
    notes: "Giresun kalite tombul fındık",
  },
];

export const INITIAL_HARVESTS: HarvestRecord[] = [
  {
    id: "h-1",
    date: "2026-05-24",
    year: 2026,
    season: "season_1",
    gardenId: "g-1",
    gardenName: "Çayeli Yamaç Çaylığı",
    quantityKg: 1850,
    buyerName: "ÇAYKUR Çayeli Fabrikası",
    unitPriceGross: 35.0,
    grossAmount: 64750,
    deductionRate: 0.02,
    deductionAmount: 1295,
    netReceivable: 63455,
    collectedAmount: 63455,
    dueDate: "2026-06-30",
    status: "completed",
    receiptNote: "1. Sürüm ÇAYKUR alımı - Tamamı ödendi",
    cropType: "tea",
    paymentOption: "aylik",
    paymentTerms: "Aylık (30 Gün)",
  },
  {
    id: "h-2",
    date: "2026-07-16",
    year: 2026,
    season: "season_2",
    gardenId: "g-1",
    gardenName: "Çayeli Yamaç Çaylığı",
    quantityKg: 2150,
    buyerName: "Doğuş Çay Alım Yeri",
    unitPriceGross: 36.5,
    grossAmount: 78475,
    deductionRate: 0.02,
    deductionAmount: 1569.5,
    netReceivable: 76905.5,
    collectedAmount: 50000,
    dueDate: "2026-08-30",
    status: "partial",
    receiptNote: "2. Sürüm - 26.905,50 TL bakiye bekliyor",
    cropType: "tea",
    paymentOption: "vadeli",
    paymentTerms: "Vadeli (%60 Peşin + 45 Gün)",
  },
  {
    id: "h-3",
    date: "2026-08-20",
    year: 2026,
    season: "season_3",
    gardenId: "g-2",
    gardenName: "Of Kıyıcık Sahil Çaylığı",
    quantityKg: 1400,
    buyerName: "Ofçay Karadeniz Fabrikası",
    unitPriceGross: 35.8,
    grossAmount: 50120,
    deductionRate: 0.02,
    deductionAmount: 1002.4,
    netReceivable: 49117.6,
    collectedAmount: 0,
    dueDate: "2026-09-30",
    status: "pending",
    receiptNote: "3. Sürüm hasadı - Vadeli alacak",
    cropType: "tea",
    paymentOption: "vadeli",
    paymentTerms: "Vadeli (30 Gün)",
  },
  {
    id: "h-4",
    date: "2026-10-10",
    year: 2026,
    season: "season_4",
    gardenId: "g-1",
    gardenName: "Çayeli Yamaç Çaylığı",
    quantityKg: 950,
    buyerName: "ÇAYKUR Çayeli Fabrikası",
    unitPriceGross: 35.0,
    grossAmount: 33250,
    deductionRate: 0.02,
    deductionAmount: 665,
    netReceivable: 32585,
    collectedAmount: 0,
    dueDate: "2026-11-15",
    status: "pending",
    receiptNote: "4. Sürüm (Son Sürüm) alımı",
    cropType: "tea",
  },
  {
    id: "h-5",
    date: "2025-05-20",
    year: 2025,
    season: "season_1",
    gardenId: "g-1",
    gardenName: "Çayeli Yamaç Çaylığı",
    quantityKg: 1720,
    buyerName: "ÇAYKUR Çayeli Fabrikası",
    unitPriceGross: 24.5,
    grossAmount: 42140,
    deductionRate: 0.02,
    deductionAmount: 842.8,
    netReceivable: 41297.2,
    collectedAmount: 41297.2,
    dueDate: "2025-06-30",
    status: "completed",
    receiptNote: "2025 1. Sürüm - Tahsil edildi",
    cropType: "tea",
  },
  {
    id: "h-6",
    date: "2025-07-18",
    year: 2025,
    season: "season_2",
    gardenId: "g-1",
    gardenName: "Çayeli Yamaç Çaylığı",
    quantityKg: 1980,
    buyerName: "Doğuş Çay",
    unitPriceGross: 25.0,
    grossAmount: 49500,
    deductionRate: 0.02,
    deductionAmount: 990,
    netReceivable: 48510,
    collectedAmount: 48510,
    dueDate: "2025-08-30",
    status: "completed",
    receiptNote: "2025 2. Sürüm - Tahsil edildi",
    cropType: "tea",
  },
  {
    id: "h-7",
    date: "2025-08-25",
    year: 2025,
    season: "season_3",
    gardenId: "g-2",
    gardenName: "Of Kıyıcık Sahil Çaylığı",
    quantityKg: 1350,
    buyerName: "Ofçay Karadeniz Fabrikası",
    unitPriceGross: 24.8,
    grossAmount: 33480,
    deductionRate: 0.02,
    deductionAmount: 669.6,
    netReceivable: 32810.4,
    collectedAmount: 32810.4,
    dueDate: "2025-09-30",
    status: "completed",
    receiptNote: "2025 3. Sürüm - Tahsil edildi",
    cropType: "tea",
  },
];

export const INITIAL_PAYMENTS: PaymentRecord[] = [
  {
    id: "p-1",
    harvestId: "h-1",
    date: "2026-06-28",
    amount: 63455,
    note: "ÇAYKUR 1. Sürüm Ziraat Bankası Hesabına Yatırıldı",
    paymentMethod: "bank",
  },
  {
    id: "p-2",
    harvestId: "h-2",
    date: "2026-08-05",
    amount: 50000,
    note: "Doğuş Çay 1. Taksit Havalesi",
    paymentMethod: "bank",
  },
];

export const INITIAL_EXPENSES: ExpenseRecord[] = [
  {
    id: "e-1",
    date: "2026-04-12",
    category: "fertilizer",
    title: "10 Çuval 25-5-10 Özel Çay Gübresi",
    amount: 14500,
    gardenId: "g-1",
    gardenName: "Çayeli Yamaç Çaylığı",
    note: "Kooperatiften peşin alım, bahçenin üst yamacına serpildi",
  },
  {
    id: "e-2",
    date: "2026-05-22",
    category: "labor_crew",
    title: "1. Sürüm Çavuş Mehmet Ekibi Yevmiyesi (4 Kişi x 2 Gün)",
    amount: 16000,
    gardenId: "g-1",
    gardenName: "Çayeli Yamaç Çaylığı",
    note: "Kişi başı 2.000 TL net yevmiye, peşin ödendi",
  },
  {
    id: "e-3",
    date: "2026-07-15",
    category: "fuel_tools",
    title: "Motorlu Çay Budama Tırpanı Bakım & Benzin",
    amount: 2450,
    gardenId: "g-2",
    gardenName: "Of Kıyıcık Sahil Çaylığı",
    note: "Buji ve misina yenileme, 20L benzin alımı",
  },
  {
    id: "e-4",
    date: "2026-08-05",
    category: "labor_crew",
    title: "Fındık Alt Temizliği ve Dal Budama Yevmiyesi",
    amount: 9000,
    gardenId: "g-3",
    gardenName: "Tirebolu Fındık Bahçesi",
    note: "3 kişilik ekip ile tırpan ve ot temizliği tamamlandı",
  },
];

export const FACTORY_PRICES: FactoryPrice[] = [
  {
    id: "f-1",
    factoryName: "ÇAYKUR (Devlet Alımı)",
    crop: "tea",
    basePrice: 35.0,
    supportPayment: 3.5,
    paymentOption: "aylik",
    paymentValues: {
      aylik: "35.00 TL (Ay sonu / 30 gün içinde banka hesabına)",
    },
    customPaymentDetail: "Ay sonu / 30 gün içinde banka hesabına aktarım",
    paymentTerms: "Aylık (30 Gün İçinde)",
    effectiveDate: "2026 Sezonu",
    note: "Kontenjanlı alım, destekleme primi ayrıca ödenir.",
    isUserAdded: false,
  },
  {
    id: "f-2",
    factoryName: "Doğuş Çay",
    crop: "tea",
    basePrice: 36.5,
    supportPayment: 0,
    paymentOption: "vadeli",
    paymentValues: {
      pesin: "35.50 TL (%60 Kantarda Peşin)",
      vadeli: "37.50 TL (%40 Kalan 45 Gün Vadeli)",
    },
    customPaymentDetail: "Peşin %60, Kalan 45 Gün Vadeli",
    paymentTerms: "Vadeli (Peşin %60 + 45 Gün)",
    effectiveDate: "2026 Sezonu",
    note: "Serbest kota, kantar teslimi.",
    isUserAdded: false,
  },
  {
    id: "f-3",
    factoryName: "Ofçay (JDE)",
    crop: "tea",
    basePrice: 35.8,
    supportPayment: 0,
    paymentOption: "vadeli",
    paymentValues: {
      aylik: "35.80 TL (30 Gün Vadeli Havale)",
      vadeli: "36.50 TL (60 Gün Vadeli Alım)",
    },
    customPaymentDetail: "30 Gün Vadeli Havale",
    paymentTerms: "Vadeli (30 Gün)",
    effectiveDate: "2026 Sezonu",
    note: "Kaliteli taze 2.5 yaprak alımı.",
    isUserAdded: false,
  },
  {
    id: "f-4",
    factoryName: "Lipton / Ekoterra",
    crop: "tea",
    basePrice: 37.0,
    supportPayment: 0,
    paymentOption: "haftalik",
    paymentValues: {
      haftalik: "37.00 TL (Her Cuma haftalık teslimat ödemesi)",
    },
    customPaymentDetail: "Her Cuma haftalık teslimat ödemesi",
    paymentTerms: "Haftalık (Her Cuma)",
    effectiveDate: "2026 Sezonu",
    note: "Sürdürülebilir çay tarımı sertifikalı bahçeler.",
    isUserAdded: false,
  },
  {
    id: "f-5",
    factoryName: "TMO Fındık Taban Fiyatı (Giresun Kalite)",
    crop: "hazelnut",
    basePrice: 195.0,
    supportPayment: 5.0,
    paymentOption: "aylik",
    paymentValues: {
      aylik: "195.00 TL (21 Gün içinde Ziraat Bankası)",
    },
    customPaymentDetail: "21 Gün içinde Ziraat Bankası",
    paymentTerms: "Aylık (21 Gün İçinde)",
    effectiveDate: "2026 Sezonu",
    note: "%50 randıman esası, randıman farkı eklenir.",
    isUserAdded: false,
  },
  {
    id: "f-6",
    factoryName: "Serbest Piyasa Tüccar (Levant Kalite)",
    crop: "hazelnut",
    basePrice: 185.0,
    paymentOption: "pesin",
    paymentValues: {
      pesin: "185.00 TL (Harman başı kantar teslimi peşin nakit)",
    },
    customPaymentDetail: "Harman başı kantar teslimi peşin nakit",
    paymentTerms: "Peşin (Kantarda Nakit)",
    effectiveDate: "2026 Sezonu",
    note: "Harman başı peşin ödeme.",
    isUserAdded: false,
  },
];

const nowMs = Date.now();
const DAY_MS = 24 * 60 * 60 * 1000;

export const INITIAL_JOBS: JobListing[] = [
  {
    id: "j-1",
    employerId: "user-ahmet-producer",
    title: "3. Sürüm Çay Hasadı İçin 5 Kişilik Deneyimli Ekip",
    employerName: "Ahmet Kavalcı (Bahçe Sahibi)",
    employerPhone: "0532 411 28 53",
    phone: "0532 411 28 53",
    locationCity: "Rize",
    locationDistrict: "Çayeli",
    cropType: "tea",
    gardenSizeDonum: 8.0,
    workerCount: 5,
    startDate: "2026-09-18",
    estimatedDays: 4,
    paymentType: "daily_wage",
    wageAmount: 2200, // Kesin yevmiye (pazarlık kesinlikle yasaktır!)
    hasAccommodation: true,
    hasFood: true,
    hasTransportation: true,
    notes: "Yamaç bahçe, çuval çekme teleferiği mevcuttur. Net yevmiye her akşam peşin ödenir.",
    status: "active",
    createdAt: "Bugün",
    createdAtTimestamp: nowMs - 2 * DAY_MS,
    expiresAtTimestamp: nowMs + 5 * DAY_MS,
    applicantsCount: 3,
  },
  {
    id: "j-2",
    employerId: "user-mustafa-hazelnut",
    title: "Tirebolu Fındık Toplama İşi - 8 Kişilik Grup",
    employerName: "Mustafa Çakır",
    employerPhone: "0544 322 19 28",
    phone: "0544 322 19 28",
    locationCity: "Giresun",
    locationDistrict: "Tirebolu",
    cropType: "hazelnut",
    gardenSizeDonum: 14.0,
    workerCount: 8,
    startDate: "2026-08-15",
    estimatedDays: 10,
    paymentType: "daily_wage",
    wageAmount: 1800,
    hasAccommodation: true,
    hasFood: true,
    hasTransportation: false,
    notes: "Köy evi konaklaması tahsis edilecektir. Çavuş liderliğinde blok anlaşmalı başvuru kabul edilir.",
    status: "active",
    createdAt: "Dün",
    createdAtTimestamp: nowMs - 1 * DAY_MS,
    expiresAtTimestamp: nowMs + 6 * DAY_MS,
    applicantsCount: 5,
  },
  {
    id: "j-3",
    employerId: "user-mehmet-employer",
    title: "Gençleştirme Budaması (1/7) ve Motorlu Tırpan",
    employerName: "Mehmet Çepni",
    employerPhone: "0532 411 28 53",
    phone: "0532 411 28 53",
    locationCity: "Trabzon",
    locationDistrict: "Of",
    cropType: "tea",
    gardenSizeDonum: 5.0,
    workerCount: 2,
    startDate: "2026-11-20",
    estimatedDays: 6,
    paymentType: "lump_sum",
    wageAmount: 32000, // Kesin götürü tutar
    hasAccommodation: false,
    hasFood: true,
    hasTransportation: true,
    notes: "5 dönüm çaylık 15 cm'den budanacak. Kendi motorlu tırpanı olan ustalar aranıyor.",
    status: "active",
    createdAt: "3 gün önce",
    createdAtTimestamp: nowMs - 3 * DAY_MS,
    expiresAtTimestamp: nowMs + 4 * DAY_MS,
    applicantsCount: 2,
  },
  {
    id: "j-4-expired",
    employerId: "user-ahmet-producer",
    title: "2. Sürüm Çay Budama ve Temizlik İşi (Süresi Dolan İlan)",
    employerName: "Ahmet Kavalcı (Bahçe Sahibi)",
    employerPhone: "0532 411 28 53",
    phone: "0532 411 28 53",
    locationCity: "Rize",
    locationDistrict: "Pazar",
    cropType: "tea",
    gardenSizeDonum: 6.0,
    workerCount: 3,
    startDate: "2026-09-01",
    estimatedDays: 5,
    paymentType: "daily_wage",
    wageAmount: 2100,
    hasAccommodation: true,
    hasFood: true,
    hasTransportation: true,
    notes: "Bu ilanın 7 günlük yayın süresi dolmuştur. Sistem tarafından otomatik olarak pasife alınmış ve diğer kullanıcılara gizlenmiştir. İlan sahibi tek tıkla tekrar aktif edebilir.",
    status: "inactive",
    createdAt: "10 gün önce",
    createdAtTimestamp: nowMs - 10 * DAY_MS,
    expiresAtTimestamp: nowMs - 3 * DAY_MS,
    applicantsCount: 1,
  },
];

export const INITIAL_CREWS: CrewLeaderProfile[] = [
  {
    id: "c-1",
    name: "Çavuş Mehmet Yılmaz",
    phone: "0535 882 14 00",
    location: "Rize / Pazar",
    city: "Rize",
    district: "Pazar",
    crewSize: 12,
    specialties: ["Usta Çay Makasçısı", "Motorlu Tırpancı", "Çuvalcı", "Teleferikçi"],
    experienceYears: 14,
    expectedDailyWagePerPerson: 2200,
    availableDates: "15 Eylül - 10 Ekim arası müsait",
    rating: 4.9,
    verified: true,
    members: [
      { id: "cm-1", name: "Dursun K.", roleTitle: "Makasçı", phone: "0532 111 22 33", dailyWage: 2200 },
      { id: "cm-2", name: "Hasan Y.", roleTitle: "Makasçı", phone: "0533 222 33 44", dailyWage: 2200 },
      { id: "cm-3", name: "İsmail A.", roleTitle: "Motorlu Tırpancı", phone: "0534 333 44 55", dailyWage: 2400 },
      { id: "cm-4", name: "Recep Ç.", roleTitle: "Çuvalcı", phone: "0535 444 55 66", dailyWage: 2000 },
      { id: "cm-5", name: "Ali B.", roleTitle: "Teleferikçi", phone: "0536 555 66 77", dailyWage: 2200 },
    ],
  },
  {
    id: "c-2",
    name: "Çavuş Dursun Genç",
    phone: "0542 611 78 90",
    location: "Trabzon / Sürmene",
    city: "Trabzon",
    district: "Sürmene",
    crewSize: 8,
    specialties: ["Fındık Hasadı", "Çay Budama", "Çuval Taşıma", "Yamaç Arazi"],
    experienceYears: 9,
    expectedDailyWagePerPerson: 2000,
    availableDates: "Ağustos ve Eylül tamamı",
    rating: 4.8,
    verified: true,
    members: [
      { id: "cm-6", name: "Kemal T.", roleTitle: "Usta", phone: "0537 666 77 88", dailyWage: 2000 },
      { id: "cm-7", name: "Osman D.", roleTitle: "Makasçı", phone: "0538 777 88 99", dailyWage: 2000 },
    ],
  },
];

export const INITIAL_WORKERS: WorkerProfile[] = [
  {
    id: "w-1",
    name: "Murat Demir",
    phone: "0531 200 45 77",
    location: "Rize / Merkez",
    city: "Rize",
    skills: ["Usta Çay Makasçısı", "Motorlu Tırpan", "Çuval Taşıma", "Teleferik Kullanımı"],
    experienceYears: 8,
    expectedDailyWage: 2200,
    availability: "Hafta içi ve hafta sonu tam zamanlı",
    availabilityStatus: "available",
    rating: 5.0,
    reviewCount: 24,
    description: "Günde 400-450 kg çay biçerim. Yamaç ve teleferik arazisinde deneyimliyim.",
    references: "Kavalcı Çay Bahçeleri (Ahmet Bey), Çayeli Kooperatifi",
  },
  {
    id: "w-2",
    name: "Cemal Kaya",
    phone: "0537 912 34 88",
    location: "Artvin / Arhavi",
    city: "Artvin",
    skills: ["Çay Budama", "Gübreleme Dağıtımı", "Motorlu Tırpan"],
    experienceYears: 12,
    expectedDailyWage: 2400,
    availability: "Ekim - Mart dönemi budama işleri",
    availabilityStatus: "available",
    rating: 4.9,
    reviewCount: 31,
    description: "1/7 gençleştirme budaması ve dip temizliğinde usta sertifikalıyım.",
    references: "Arhavi Ziraat Odası, Dursun Çavuş",
  },
  {
    id: "w-3",
    name: "Emre Balcı",
    phone: "0543 890 12 34",
    location: "Giresun / Espiye",
    city: "Giresun",
    skills: ["Fındık Toplama", "Çuval Taşıma", "Harman Kurutma"],
    experienceYears: 5,
    expectedDailyWage: 1900,
    availability: "Sezon boyunca müsait",
    availabilityStatus: "available",
    rating: 4.7,
    reviewCount: 16,
    description: "Fındık toplama ve sırtta çuval taşıma işlerinde güçlüyüm.",
    references: "Espiye Fındık Birliği",
  },
];

export const INITIAL_APPLICATIONS: JobApplication[] = [
  {
    id: "app-1",
    jobId: "j-1",
    jobTitle: "3. Sürüm Çay Hasadı İçin 5 Kişilik Deneyimli Ekip",
    applicantName: "Çavuş Mehmet Yılmaz",
    applicantPhone: "0535 882 14 00",
    applicantRole: "crew_leader",
    teamSize: 5,
    demandedWage: 2200,
    offerNote: "5 kişilik usta makasçı kadromla belirtilen tarihte işe hazırız. Teleferik ve yamaç tecrübemiz tamdır.",
    status: "pending",
    createdAt: "13 Eylül 2026 14:30",
  },
  {
    id: "app-2",
    jobId: "j-1",
    jobTitle: "3. Sürüm Çay Hasadı İçin 5 Kişilik Deneyimli Ekip",
    applicantName: "Murat Demir",
    applicantPhone: "0531 200 45 77",
    applicantRole: "worker",
    teamSize: 1,
    demandedWage: 2200,
    offerNote: "Bireysel usta makasçı olarak katılabilirim, günlük 400 kg üzeri hasat garantisi veriyorum.",
    status: "accepted",
    createdAt: "13 Eylül 2026 10:15",
  },
  {
    id: "app-3",
    jobId: "j-2",
    jobTitle: "Tirebolu Fındık Toplama İşi - 8 Kişilik Grup",
    applicantName: "Çavuş Dursun Genç",
    applicantPhone: "0542 611 78 90",
    applicantRole: "crew_leader",
    teamSize: 8,
    demandedWage: 1800,
    offerNote: "8 kişilik toplama ekibiyle köy evi konaklamalı şekilde 10 gün içinde bahçeyi bitiririz.",
    status: "pending",
    createdAt: "11 Eylül 2026 16:45",
  },
];

export const INITIAL_SERVICES: ServiceOffer[] = [
  {
    id: "so-1",
    title: "1/7 & 1/10 Gençleştirme Budaması ve Dip Temizliği",
    category: "pruning",
    providerName: "Usta Budama & Tarım Hizmetleri (Şaban Usta)",
    providerPhone: "0538 450 11 22",
    city: "Rize / Çayeli",
    pricingUnit: "donum",
    priceAmount: 4500, // Dönüm başı net fiyat
    description: "Ruhsatlı gençleştirme budaması, 15-20 cm toprak üstü kesim, aşı macunlama ve dal temizliği.",
    rating: 4.9,
  },
  {
    id: "so-2",
    title: "Motorlu Tırpan ile Bahçe Altı Ot Temizliği",
    category: "clearing",
    providerName: "Doğu Karadeniz Tırpan Ekibi",
    providerPhone: "0532 999 88 77",
    city: "Trabzon / Of",
    pricingUnit: "donum",
    priceAmount: 1200,
    description: "Misinalı ve bıçaklı motorlu tırpanla çaylık ve fındıklık altı diken, yabancı ot temizliği.",
    rating: 4.8,
  },
  {
    id: "so-3",
    title: "Drone ile Havadan Fındık & Çay İlaçlama Hizmeti",
    category: "spraying",
    providerName: "AgroDrone Karadeniz Zirai Havacılık",
    providerPhone: "0462 333 44 55",
    city: "Giresun / Tirebolu",
    pricingUnit: "donum",
    priceAmount: 450,
    description: "T-30 Tarım Dronu ile külleme ve fındık kurdu mücadelesi. Eşit ve homojen ilaçlama.",
    rating: 5.0,
  },
  {
    id: "so-4",
    title: "Toprak pH & NPK Analizi + Reçeteli Gübreleme Raporu",
    category: "soil_analysis",
    providerName: "Karadeniz Ziraat & Toprak Analiz Laboratuvarı",
    providerPhone: "0464 213 45 67",
    city: "Rize / Merkez",
    pricingUnit: "donum",
    priceAmount: 750,
    description: "Akredite laboratuvarda pH, kireç, organik madde ve NPK ölçümü. 25-5-10 gübre kullanım reçetesi.",
    rating: 4.9,
  },
];

export const INITIAL_SERVICE_PROVIDERS: ServiceProvider[] = [
  {
    id: "sp-1",
    companyName: "Karadeniz Ziraat & Toprak Analiz Laboratuvarı",
    contactPerson: "Ziraat Müh. Hakan Akın",
    phone: "0464 213 45 67",
    location: "Rize / Merkez & İlçeleri",
    services: ["Toprak pH ve NPK Analizi", "Reçeteli Gübreleme Planı", "Kök Kanseri Tespiti"],
    pricingSummary: "Parsel başı analiz: 750 TL (Rapor dahil)",
    rating: 4.9,
  },
  {
    id: "sp-2",
    companyName: "Usta Budama & Motorlu Tarım Hizmetleri",
    contactPerson: "Şaban Usta",
    phone: "0538 450 11 22",
    location: "Trabzon & Rize Bölgesi",
    services: ["1/7 Gençleştirme Budaması", "Kök Havalandırma", "Dönüm Bazlı Temizlik"],
    pricingSummary: "Dönüm başı götürü veya tırpan saati 850 TL",
    rating: 4.8,
  },
];

// Ziraat Bilgi Tabanı: "Belirti - Zaman Çizelgesi - Uygulama"
export const AGRONOMY_KNOWLEDGE_BASE = [
  {
    id: "disease-kulleme",
    category: "Hastalık ve Zararlılar",
    title: "Külleme Hastalığı (Unluca / Erysiphe)",
    targetCrop: "Fındık & Çay",
    symptom: "Yaprakların alt ve üst yüzeyinde una benzer beyaz küf lekeleri, erken sararma ve kuruma, çotanakların iç dolduramaması.",
    timeline: "İlkbahar (Nisan sonu - Mayıs ayı). Yağmurlu ve nemli 18-24°C sıcaklıkta hızla yayılır.",
    application: "Bahçe içi hava akımını sağlamak için dip sürgünleri temizlenmeli, bitki koruma ürünleri (onaylı kükürt ve fungisitler) ilk belirtiler görülür görülmez sabahın erken saatlerinde homojen şekilde püskürtülmelidir.",
    dangerLevel: "Yüksek",
  },
  {
    id: "pest-findik-kurdu",
    category: "Hastalık ve Zararlılar",
    title: "Fındık Kurdu (Curculio nucum)",
    targetCrop: "Fındık",
    symptom: "Fındık meyvelerinde mercimek iriliğindeyken delikler, sarı ve kara döküm (içi boş dökülen fındıklar).",
    timeline: "Mayıs ayı başı. Hava sıcaklığı 16°C üzerine çıktığında ocak başına 2-3 ergin böcek düştüğünde.",
    application: "Sabahın erken serinliğinde ocaklar beyaz bez üstüne silkelenerek sayım yapılır. Eşik aşıldığında ruhsatlı insektisit ile tüm bahçe aynı gün ilaçlanır.",
    dangerLevel: "Kritik",
  },
  {
    id: "disease-canker",
    category: "Hastalık ve Zararlılar",
    title: "Dal Kanseri (Canker / Botryosphaeria)",
    targetCrop: "Çay & Fındık",
    symptom: "Gövde ve kalın dallarda çöküntülü, çatlamış yaralar, nekroz dokular ve dalın uçtan geriye doğru kuruması.",
    timeline: "Sonbahar ve erken ilkbahar budama döneminde bulaşma riski en yüksektir.",
    application: "Hastalıklı dallar yaranın 15-20 cm altından sağlıklı dokudan kesilip yakılmalı, budama aletleri çamaşır suyu veya alkolle dezenfekte edilmeli, kesim yüzeylerine aşı macunu sürülmelidir.",
    dangerLevel: "Orta-Yüksek",
  },
  {
    id: "disease-kok-curuklugu",
    category: "Hastalık ve Zararlılar",
    title: "Kök Çürüklüğü (Armillaria & Rosellinia)",
    targetCrop: "Çay",
    symptom: "Ocaklarda ani solma, yaprak dökümü, kök kabuğu kaldırıldığında beyaz mantar miselleri ve çürümüş odun dokusu.",
    timeline: "Aşırı yağış alan, su biriken taban arazilerde yıl boyunca gelişebilir.",
    application: "Drenaj kanalları açılarak kök bölgesinde su göllenmesi önlenmeli, kurumuş ocaklar kökleriyle birlikte sökülüp yakılmalı ve çukur kireçle dezenfekte edilmelidir.",
    dangerLevel: "Kritik",
  },
  {
    id: "nutrition-npk",
    category: "Bitki Besleme",
    title: "Çay ve Fındıkta N-P-K & Mikro Elementler",
    targetCrop: "Çay ve Fındık",
    symptom: "Yaprak sararması (Azot noksanlığı), sürgün cılızlığı (Fosfor), hastalıklara dayanıksızlık (Potasyum), meyve içi boşluğu (Bor ve Çinko).",
    timeline: "Taban gübresi: Mart - Nisan. Ara takviyeler: 1. ve 2. sürüm hasadından hemen sonra.",
    application: "Çayda 25-5-10 formülasyonlu kompoze gübre dekara 60-80 kg ocak izdüşümüne verilir. Asla kök boğazına yığılmamalıdır. Fındıkta kış sonu Bor+Çinko yaprak gübresi döllenmeyi katlar.",
    dangerLevel: "Temel İhtiyaç",
  },
  {
    id: "pruning-renovation",
    category: "Budama",
    title: "Gençleştirme Budaması (1/7 ve 1/10 Kuralı)",
    targetCrop: "Çay",
    symptom: "Ocakların kartlaşması, sürgün boyunun 5 cm altına düşmesi, hasatta makasın takılması ve işçilik süresinin 2 katına çıkması.",
    timeline: "Kasım ortasından Mart sonuna kadar (çay bitkisi dinlenme dönemindeyken).",
    application: "Bahçenin her yıl 1/7'si topraktan 15-20 cm yükseklikten motorlu tırpan veya budama makasıyla gençleştirilir. Bu uygulama taze sürgün verdiği için hasat işçilik maliyetlerini kalıcı olarak %30 düşürür.",
    dangerLevel: "Yüksek Verim Anahtarı",
  },
];

export const MONTHLY_CALENDAR = [
  {
    month: "Ocak",
    crop: "Çay & Fındık",
    task: "Kış dinlenme dönemi. Budama artıkları temizliği, bahçe drenaj kanalları açılması.",
    crewNotice: "Yeni sezon işçi bağlantıları için planlama aşaması.",
  },
  {
    month: "Şubat",
    crop: "Çay & Fındık",
    task: "Toprak tahlili numunelerinin alınması. Fındıkta kireçleme ve kış budamasının tamamlanması.",
    crewNotice: "Çavuşlarla ön görüşmeler.",
  },
  {
    month: "Mart",
    crop: "Çay & Fındık",
    task: "Çayda taban gübresi (25-5-10) uygulaması. Budama dönemi sonu.",
    crewNotice: "1. Sürüm hasat ekipleri sözleşmelerini kesinleştirin.",
  },
  {
    month: "Nisan",
    crop: "Çay & Fındık",
    task: "Yabancı ot mücadelesi, külleme ve dip sürgünü temizliği. Fındıkta yaprak gübresi.",
    crewNotice: "1. Sürüm ekipleri 3 hafta önceden kesinleştirilmeli!",
  },
  {
    month: "Mayıs",
    crop: "Çay",
    task: "1. Sürüm Yaş Çay Hasadı başlangıcı. Fındık kurdu ilaçlaması.",
    crewNotice: "Hasat dönemi: Yüksek işgücü talebi!",
  },
  {
    month: "Haziran",
    crop: "Çay & Fındık",
    task: "1. Sürüm sonu ve ara gübreleme. Fındıkta ikinci külleme kontrolü.",
    crewNotice: "2. Sürüm için çavuş rezervasyonu yenileme.",
  },
  {
    month: "Temmuz",
    crop: "Çay",
    task: "2. Sürüm Yaş Çay Hasadı. Bahçe temizliği.",
    crewNotice: "Fındık toplama ekipleriyle tarih sabitleme.",
  },
  {
    month: "Ağustos",
    crop: "Fındık & Çay",
    task: "Fındık hasadı başlangıcı & 3. Sürüm çay hasadı hazırlığı.",
    crewNotice: "Karadeniz'in en yoğun işgücü ayı!",
  },
  {
    month: "Eylül",
    crop: "Çay & Fındık",
    task: "3. Sürüm yaş çay hasadı tamamlanması. Fındık kurutma ve patoz.",
    crewNotice: "Hasat hesaplaşmaları ve tahsilat takibi.",
  },
  {
    month: "Ekim",
    crop: "Çay & Fındık",
    task: "Sonbahar dip temizliği, harman sonu bakımları.",
    crewNotice: "Kış dönemi budama işleri planlaması.",
  },
  {
    month: "Kasım",
    crop: "Çay",
    task: "1/7 Gençleştirme budaması başlangıcı.",
    crewNotice: "Budama ustaları ile anlaşma.",
  },
  {
    month: "Aralık",
    crop: "Çay & Fındık",
    task: "Budama devamı, organik gübre ve kış bakımı.",
    crewNotice: "Gelecek sezon hazırlığı.",
  },
];

export const INITIAL_AGRI_PRODUCTS: AgriProductListing[] = [
  {
    id: "prod-1",
    title: "Kabuklu Fındık (Yeni Sezon Randımanlı)",
    category: "hazelnut",
    categoryLabel: "Fındık",
    price: 2200,
    unit: "50 kg",
    quantity: "2.500 kg (50 çuval)",
    locationCity: "Samsun",
    locationDistrict: "Çarşamba",
    locationNeighborhood: "Aşağı Kavacık",
    sellerName: "Mustafa Çakır",
    sellerPhone: "0544 322 19 28",
    sellerType: "producer",
    verified: true,
    rating: 4.9,
    reviewCount: 18,
    images: [
      "https://images.unsplash.com/photo-1543257580-7269da773bf5?auto=format&fit=crop&w=600&q=80",
    ],
    description: "Yeni sezon kurutulmuş, patozdan yeni çıkmış %52 randımanlı tombul fındık. Çuvalı 50 kg tartılarak doğrudan çiftliğimizden teslim edilir.",
    harvestYear: 2026,
    createdAt: "Dün",
    featured: true,
    minOrder: "1 Çuval (50 kg)",
  },
  {
    id: "prod-2",
    title: "1. Sürüm Mayıs Çayı (Taze Yaş Çay)",
    category: "tea",
    categoryLabel: "Çay",
    price: 38,
    unit: "kg",
    quantity: "1.200 kg",
    locationCity: "Rize",
    locationDistrict: "Çayeli",
    locationNeighborhood: "Kaptanpaşa Köyü",
    sellerName: "Ahmet Kavalcı",
    sellerPhone: "0532 411 28 53",
    sellerType: "producer",
    verified: true,
    rating: 5.0,
    reviewCount: 32,
    images: [
      "https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=600&q=80",
    ],
    description: "Yüksek rakımlı yamaç bahçesinden el makasıyla toplanmış birinci sınıf 2.5 yaprak körpe mayıs çayı. Özel butik işleme veya fabrika teslimine hazır.",
    harvestYear: 2026,
    createdAt: "Bugün",
    featured: true,
    minOrder: "100 kg",
  },
  {
    id: "prod-3",
    title: "Taş Değirmen Karadeniz Sarı Mısır Unu",
    category: "corn",
    categoryLabel: "Mısır",
    price: 180,
    unit: "5 kg",
    quantity: "40 çuval",
    locationCity: "Trabzon",
    locationDistrict: "Akçaabat",
    locationNeighborhood: "Söğütlü",
    sellerName: "Fadime Nine Çiftliği",
    sellerPhone: "0538 912 34 56",
    sellerType: "producer",
    verified: true,
    rating: 4.8,
    reviewCount: 24,
    images: [
      "https://images.unsplash.com/photo-1551754655-cd27e38d2076?auto=format&fit=crop&w=600&q=80",
    ],
    description: "Geleneksel su değirmeninde öğütülmüş, yerli tohum sarı mısır unu. Mıhlama ve mısır ekmeği için ideal kıvamda, katkısız ve taze.",
    harvestYear: 2026,
    createdAt: "3 gün önce",
    featured: false,
    minOrder: "1 Paket (5 kg)",
  },
  {
    id: "prod-4",
    title: "Doğal Trabzon Hurması (Cennet Elması)",
    category: "fruit",
    categoryLabel: "Meyve",
    price: 85,
    unit: "kg",
    quantity: "350 kg",
    locationCity: "Trabzon",
    locationDistrict: "Vakfıkebir",
    locationNeighborhood: "Yalıköy",
    sellerName: "Hasan Reis",
    sellerPhone: "0533 444 55 66",
    sellerType: "producer",
    verified: false,
    rating: 4.7,
    reviewCount: 9,
    images: [
      "https://images.unsplash.com/photo-1596363505729-4190a9506133?auto=format&fit=crop&w=600&q=80",
    ],
    description: "Bahçemizden dalından taze toplanmış tatlı Trabzon hurması. İster taze tüketim ister kurutmalık için sert ve olgun seçenekler mevcuttur.",
    harvestYear: 2026,
    createdAt: "1 hafta önce",
    featured: false,
    minOrder: "10 kg",
  },
  {
    id: "prod-5",
    title: "Taze Bağ Karalahana & Taze Fasulye",
    category: "vegetable",
    categoryLabel: "Sebze",
    price: 45,
    unit: "bağ",
    quantity: "120 bağ",
    locationCity: "Ordu",
    locationDistrict: "Ünye",
    locationNeighborhood: "Tekkiraz",
    sellerName: "Emine Çelik",
    sellerPhone: "0536 777 88 99",
    sellerType: "producer",
    verified: true,
    rating: 4.9,
    reviewCount: 15,
    images: [
      "https://images.unsplash.com/photo-1524179091875-bf99a9a6fa57?auto=format&fit=crop&w=600&q=80",
    ],
    description: "İlaçsız, doğal gübreyle yetiştirilmiş körpe Karadeniz karalahanası. Günlük sabah erken hasat edilerek bağ halinde teslim edilir.",
    harvestYear: 2026,
    createdAt: "Bugün",
    featured: false,
    minOrder: "5 Bağ",
  },
  {
    id: "prod-6",
    title: "Hakiki Anzer Yayla Çiçek Balı & Köy Tereyağı",
    category: "livestock",
    categoryLabel: "Hayvancılık",
    price: 1950,
    unit: "kg",
    quantity: "45 kg",
    locationCity: "Rize",
    locationDistrict: "İkizdere",
    locationNeighborhood: "Anzer Ballıköy Yaylası",
    sellerName: "İsmail Koç (Arıcı)",
    sellerPhone: "0532 555 12 34",
    sellerType: "cooperative",
    verified: true,
    rating: 5.0,
    reviewCount: 42,
    images: [
      "https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&w=600&q=80",
    ],
    description: "3.000 metre rakımlı Anzer yaylasından tescilli flora balı. Laboratuvar polen analizi onaylı, mühürlü kavanozlarda güvenle gönderilir.",
    harvestYear: 2026,
    createdAt: "4 gün önce",
    featured: true,
    minOrder: "1 Kavanoz (1 kg)",
  },
  {
    id: "prod-7",
    title: "Giresun Kalite Kavrulmuş İç Fındık",
    category: "hazelnut",
    categoryLabel: "Fındık",
    price: 540,
    unit: "kg",
    quantity: "150 kg",
    locationCity: "Giresun",
    locationDistrict: "Tirebolu",
    locationNeighborhood: "Doğankent Yolu",
    sellerName: "Tirebolu Üretici Kooperatifi",
    sellerPhone: "0542 987 65 43",
    sellerType: "cooperative",
    verified: true,
    rating: 4.9,
    reviewCount: 38,
    images: [
      "https://images.unsplash.com/photo-1508061252227-0c3373ab2b93?auto=format&fit=crop&w=600&q=80",
    ],
    description: "Vakumlu 1 kg'lık paketlerde taze kavrulmuş Giresun tombul fındığı. Çifte kavrulmuş, çıtır ve aromatik lezzet.",
    harvestYear: 2026,
    createdAt: "5 gün önce",
    featured: true,
    minOrder: "2 kg",
  },
  {
    id: "prod-8",
    title: "Özel Harman Karadeniz Kuru Çay (Hakiki Mayıslık)",
    category: "tea",
    categoryLabel: "Çay",
    price: 340,
    unit: "kg",
    quantity: "200 kg",
    locationCity: "Rize",
    locationDistrict: "Ardeşen",
    locationNeighborhood: "Fırtına Vadisi",
    sellerName: "Recep Usta Butik Çay",
    sellerPhone: "0535 666 43 21",
    sellerType: "producer",
    verified: true,
    rating: 4.8,
    reviewCount: 29,
    images: [
      "https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=600&q=80",
    ],
    description: "Kendi çaylığımızın mayıs sürümünden odun ateşinde fırınlanmış katkısız siyah kuru çay. Berrak dem rengi ve buruk hoş lezzet.",
    harvestYear: 2026,
    createdAt: "2 gün önce",
    featured: false,
    minOrder: "3 kg",
  },
];

export const INITIAL_MARKET_MESSAGES: MarketMessage[] = [
  {
    id: "msg-1",
    listingId: "prod-1",
    listingTitle: "Kabuklu Fındık (Yeni Sezon Randımanlı)",
    contactName: "Mustafa Çakır",
    contactPhone: "0544 322 19 28",
    lastMessage: "Merhaba, 10 çuval için yarın Çarşamba merkezde teslimat yapabiliriz.",
    timestamp: "14:25",
    unread: true,
  },
  {
    id: "msg-2",
    listingId: "j-1",
    listingTitle: "3. Sürüm Çay Hasadı İçin 5 Kişilik Ekip",
    contactName: "Çavuş Mehmet Yılmaz",
    contactPhone: "0535 882 14 00",
    lastMessage: "Ekibimiz hazır, teleferik kontrolünü tamamladınız mı?",
    timestamp: "Dün",
    unread: false,
  },
  {
    id: "msg-3",
    listingId: "prod-6",
    listingTitle: "Hakiki Anzer Yayla Çiçek Balı",
    contactName: "İsmail Koç",
    contactPhone: "0532 555 12 34",
    lastMessage: "Bal analiz sertifikasını kargonun içerisine ekledim.",
    timestamp: "18 Eylül",
    unread: false,
  },
];

export const INITIAL_ADMIN_MESSAGES: AdminUserMessage[] = [
  {
    id: "adm-msg-broadcast-1",
    senderId: "user-kagan-admin",
    senderName: "Kağan (Sistem Tek Yöneticisi)",
    senderRole: "admin",
    recipientId: "all",
    recipientName: "Tüm Kullanıcılar (Toplu Duyuru)",
    subject: "📢 2026 Sezonu Taban Fiyatları & Sistem Duyurusu",
    content: "Değerli Karadeniz üreticilerimiz; ÇAYKUR ve özel fabrikaların 2026 sezonu alım fiyatları ile ödeme koşulları sisteme yüklenmiştir. 'Fabrika Fiyatları' sekmesinden dilediğiniz fabrikayı ekleyebilir, kantar teslim koşullarını inceleyebilirsiniz. Sorularınız için bu bölümden bana doğrudan yazabilirsiniz. Bereketli sezonlar dilerim!",
    timestamp: "24 Eylül 2026 09:30",
    createdAt: Date.now() - 172800000,
    read: true,
    isBroadcast: true,
  },
  {
    id: "adm-msg-1",
    senderId: "user-mehmet-employer",
    senderName: "Mehmet Çepni",
    senderRole: "user",
    recipientId: "user-kagan-admin",
    recipientName: "Kağan (Ana Yönetici)",
    subject: "Çayeli Fabrikası Vadeli Ödemeleri Hakkında",
    content: "Kağan Bey hayırlı işler, Çayeli fabrikasında vadeli ödeme vadesi 45 gün olarak güncellendi mi acaba?",
    timestamp: "25 Eylül 2026 14:10",
    createdAt: Date.now() - 86400000,
    read: true,
    isBroadcast: false,
  },
  {
    id: "adm-msg-2",
    senderId: "user-kagan-admin",
    senderName: "Kağan (Sistem Tek Yöneticisi)",
    senderRole: "admin",
    recipientId: "user-mehmet-employer",
    recipientName: "Mehmet Çepni",
    subject: "Yanıt: Çayeli Fabrikası Vadeli Ödemeleri Hakkında",
    content: "Merhaba Mehmet Bey, evet kantarda %60 peşin, kalan %40 tutar için 45 gün vadeli ödeme koşulu teyit edilmiştir. Fabrika listesinden güncel durumu inceleyebilirsiniz.",
    timestamp: "25 Eylül 2026 15:00",
    createdAt: Date.now() - 82800000,
    read: true,
    isBroadcast: false,
  },
  {
    id: "adm-msg-3",
    senderId: "user-mustafa-hazelnut",
    senderName: "Mustafa Çakır",
    senderRole: "user",
    recipientId: "user-kagan-admin",
    recipientName: "Kağan (Ana Yönetici)",
    subject: "TMO Randıman Kesintisi ve Fındık Alımı",
    content: "Selamlar Kağan Bey, Çarşamba TMO fındık alımında randıman hesaplamasını sisteme nasıl girebiliriz? Peşin ödeme şartları güncellendi mi? Teşekkürler.",
    timestamp: "Dün 11:20",
    createdAt: Date.now() - 43200000,
    read: false,
    isBroadcast: false,
  },
];
